package UNLu.Poo.Uno.Modelo;

public enum EventosUNO {
    JUEGO_INICIADO,
    PUNTOS_CAMBIADOS,
    FIN_JUEGO,
    JUGADOR_AGREGADO,
    JUGADORES_MAXIMOS,
    FALTA_UNO,
    CARTA_ROBADA,
    CARTA_TIRADA,
    TURNO_CAMBIADO,
    DEBE_ROBAR,
    MISMO_NOMBRE,
    MAS4,
    MAS2,
    CAMBIACOLOR,
    BLOQUEO,
    CAMBIARONDA,
    FIN_MANO,
    JUGADA_INVALIDA,
    SOLICITAR_COLOR,
    UNO,
}
